version: '3.3'
services:
  database-kw:
    container_name: database-kw
    volumes:
      - /home/joe/kegwatch/docker/mysql:/var/lib/mysql:rw
    ports:
      - 10136:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password-1234
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev-password-1234
      - MYSQL_DATABASE=kegwatch-dev
    restart: unless-stopped 
    image: mysql  
  grafana-kw:
    container_name: grafana-kw
    volumes:
      - /home/joe/kegwatch/docker/grafana/etc:/etc/grafana:rw
      - /home/joe/kegwatch/docker/grafana/var:/var/lib/grafana:rw
    ports:
      - 10180:3000
    restart: unless-stopped
    image: grafana/grafana-oss
  api-kw:
    container_name: api-kw
    restart: unless-stopped
    image: eliharper/kegwatch-api:armv8
    ports:
      - 10288:8080
    environment:
      - USER=root
      - PW=root-password-1234
      - ADDR=database-kw
      - DB=kegwatch-dev
  ui-kw:
    container_name: ui-kw
    restart: unless-stopped
    image: eliharper/kegwatch-ui:armv8
    ports:
      - 10280:80
  mc-kw:
    container_name: mugclub-kw
    restart: unless-stopped
    image: nginx
    ports:
      - 10281:80
    volumes:
      - /home/joe/kegwatch/docker/mugclub:/usr/share/nginx/html
  game-kw:
    container_name: game-kw
    restart: unless-stopped
    image: eliharper/kw-game-svc:armv8
    ports:
      - 8082:8082
    environment:
      - USER=root
      - PW=root-password-1234
      - ADDR=database-kw
      - DB=kegwatch-dev